import React from 'react';
import { FileText, AlertTriangle, Scale, Activity } from 'lucide-react';

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      <div className="text-center space-y-2">
        <div className="inline-flex p-3 bg-blue-50 text-blue-600 rounded-2xl">
          <FileText className="w-8 h-8" />
        </div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Terms of Service &amp; Disclaimers</h1>
        <p className="text-xs text-slate-500">
          Last revised: September 2026 | AeroAqua Platform
        </p>
      </div>

      <div className="bg-white rounded-2xl p-8 border border-slate-200 shadow-sm space-y-6 text-sm text-slate-700 leading-relaxed">
        {/* Important Non-Causal Disclaimer Alert */}
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl text-amber-900 space-y-1">
          <div className="flex items-center gap-2 font-bold text-amber-950">
            <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0" />
            <span>Important Scientific &amp; Legal Non-Causal Disclaimer</span>
          </div>
          <p className="text-xs text-amber-900 leading-normal pl-7">
            Correlated factors (traffic congestion, industrial activities, construction, meteorological inversion) correlate with observed air quality anomalies but are not confirmed causes. Real-world air quality is influenced by complex atmospheric chemistry, wind dispersion, transboundary haze, and multi-factor interactions.
          </p>
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Activity className="w-4 h-4 text-blue-600" />
            1. Predictive Forecast Models (XGBoost)
          </h2>
          <p>
            Forecasts generated by the platform’s XGBoost machine learning model represent statistical estimations based on historical trend sequences, wind velocity, humidity, and baseline rolling means. Forecast values are advisory in nature and must not be used as the sole basis for life-critical decisions.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Scale className="w-4 h-4 text-blue-600" />
            2. Authority Broadcast System &amp; Emergency Directives
          </h2>
          <p>
            Only designated authorized environmental officers holding verified municipal or state credentials may issue official broadcast alerts. Citizen users agree to follow local municipal civil defense orders and official public health guidelines in the event of severe air quality or hydrological emergencies.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">3. Historical Groundwater Data Attribution</h2>
          <p>
            Groundwater metrics displayed across the platform represent historical records from the Central Ground Water Board (CGWB) / CPCB covering 2012–2021 (available via Kaggle). These records are strictly historical benchmarks and do not represent continuous real-time borehole telemetry.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">4. Open Source &amp; API Usage</h2>
          <p>
            AeroAqua makes use of OpenAQ v3 for ambient air telemetry and Open-Meteo for meteorological telemetry. Users agree to respect API rate limits and data attribution mandates.
          </p>
        </section>
      </div>
    </div>
  );
}
